Repository crowdbotics/modules, pull requests merged in 2023-08, with the labels that each got.

#924 PLAT-11697-Fix modules issues and refactor their source code
  modules/camera/modules/camera/utils.js
  modules/faq/modules/faq/FAQItem.js
  modules/faq/modules/faq/index.js
  modules/firebase-push-notifications/modules/firebase-push-notifications/index.js
  modules/react-native-appointment/screens/appointmentList.js
  modules/react-native-appointment/screens/calendar.js
  modules/react-native-appointment/screens/createAppointment.js
  modules/react-native-chat/index.js
  modules/react-native-live-camera-filters/index.js
  modules/react-native-photo-editing/Screens/crop/index.js
  modules/react-native-photo-editing/Screens/edits/index.js
  modules/react-native-photo-editing/Screens/filters/index.js
  modules/react-native-photo-editing/Screens/imagePicker/index.js
  modules/react-native-photo-editing/Screens/shadows/index.js
  modules/react-native-privacy-policy-webview/index.js
  modules/react-native-social-login/auth/apple.js
  modules/react-native-social-login/index.js
  modules/react-native-social-login/screens/loginsignup.js
  modules/react-native-social-login/screens/reset.js
  modules/react-native-terms-and-conditions-webview/index.js
  modules/react-native-typeform-webhook/options.js
  modules/react-native-zoom-free-calling/index.js
Labels: module

#774 Django S3 File-uploader
  modules/django-s3-file-uploader/django_s3_file_uploader/pyproject.toml
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/README.md
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/__init__.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/admin.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/apps.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/migrations/0001_initial.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/migrations/__init__.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/models.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/options.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/serializers.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/services/S3Service.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/tests.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/urls.py
  modules/django-s3-file-uploader/django_s3_file_uploader/s3_file_uploader/viewsets.py
  modules/django-s3-file-uploader/django_s3_file_uploader/setup.py
  modules/django-s3-file-uploader/meta.json
  modules/django-s3-file-uploader/preview.png
Labels: module

#814 Complex table module
  modules/react-native-complex-table/README.md
  modules/react-native-complex-table/components/DropDown/index.js
  modules/react-native-complex-table/components/TextInput/index.js
  modules/react-native-complex-table/index.js
  modules/react-native-complex-table/meta.json
  modules/react-native-complex-table/options.js
  modules/react-native-complex-table/package.json
  modules/react-native-complex-table/preview.png
  modules/react-native-complex-table/styles.js
Labels: module

#812 Pricing screen
  modules/screen-pricing/README.md
  modules/screen-pricing/index.js
  modules/screen-pricing/meta.json
  modules/screen-pricing/package.json
  modules/screen-pricing/preview.png
Labels: screen-only

#749 Service-provider profile and appointment detail screen
  modules/screen-service-provider-appointment-detail/assets/beat.png
  modules/screen-service-provider-appointment-detail/assets/close.png
  modules/screen-service-provider-appointment-detail/assets/heart.png
  modules/screen-service-provider-appointment-detail/assets/message.png
  modules/screen-service-provider-appointment-detail/assets/notification.png
  modules/screen-service-provider-appointment-detail/assets/phone.png
  modules/screen-service-provider-appointment-detail/index.js
  modules/screen-service-provider-appointment-detail/meta.json
  modules/screen-service-provider-appointment-detail/package.json
  modules/screen-service-provider-appointment-detail/preview.png
Labels: screen-only

#741 Schedule-appointment screen
  modules/screen-schedule-appointment/assets/back.png
  modules/screen-schedule-appointment/assets/calender.png
  modules/screen-schedule-appointment/assets/check.png
  modules/screen-schedule-appointment/assets/home.png
  modules/screen-schedule-appointment/assets/message.png
  modules/screen-schedule-appointment/assets/next.png
  modules/screen-schedule-appointment/assets/phone.png
  modules/screen-schedule-appointment/assets/prev.png
  modules/screen-schedule-appointment/assets/search.png
  modules/screen-schedule-appointment/assets/uncheck.png
  modules/screen-schedule-appointment/assets/user.png
  modules/screen-schedule-appointment/assets/video.png
  modules/screen-schedule-appointment/index.js
  modules/screen-schedule-appointment/meta.json
  modules/screen-schedule-appointment/package.json
  modules/screen-schedule-appointment/preview.png
  modules/screen-service-provider-appointment-detail/index.js
Labels: screen-only

#742 Client-profile screen
  modules/screen-client-profile/assets/bell.png
  modules/screen-client-profile/assets/calender.png
  modules/screen-client-profile/assets/home.png
  modules/screen-client-profile/assets/message.png
  modules/screen-client-profile/assets/online.png
  modules/screen-client-profile/assets/phone.png
  modules/screen-client-profile/assets/profile.png
  modules/screen-client-profile/assets/search.png
  modules/screen-client-profile/assets/sound.png
  modules/screen-client-profile/assets/user.png
  modules/screen-client-profile/index.js
  modules/screen-client-profile/meta.json
  modules/screen-client-profile/package.json
  modules/screen-client-profile/preview.png
Labels: screen-only

#719 Okta Module (Backend): Optimization for enterprise
  modules/django-okta/django_okta/__init__.py
  modules/django-okta/django_okta/okta/README.md
  modules/django-okta/django_okta/okta/__init__.py
  modules/django-okta/django_okta/okta/admin.py
  modules/django-okta/django_okta/okta/apps.py
  modules/django-okta/django_okta/okta/custom_decorator.py
  modules/django-okta/django_okta/okta/migrations/0001_initial.py
  modules/django-okta/django_okta/okta/migrations/__init__.py
  modules/django-okta/django_okta/okta/models.py
  modules/django-okta/django_okta/okta/options.py
  modules/django-okta/django_okta/okta/serializers.py
  modules/django-okta/django_okta/okta/services/okta.py
  modules/django-okta/django_okta/okta/tests.py
  modules/django-okta/django_okta/okta/urls.py
  modules/django-okta/django_okta/okta/viewsets.py
  modules/django-okta/django_okta/pyproject.toml
  modules/django-okta/django_okta/setup.py
  modules/django-okta/meta.json
  modules/django-okta/preview.png
Labels: module

#686 Firebase Push Notifications Module (Super): Optimization for enterprise
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/README.md
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/admin.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/apps.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/migrations/0001_initial.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/models.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/serializers.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/tests.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/urls.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/viewsets.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/setup.py
  modules/firebase-push-notifications/modules/firebase-push-notifications/README.md
  modules/firebase-push-notifications/modules/firebase-push-notifications/api.js
  modules/firebase-push-notifications/modules/firebase-push-notifications/flatlist.js
  modules/firebase-push-notifications/modules/firebase-push-notifications/index.js
  modules/firebase-push-notifications/modules/firebase-push-notifications/options.js
  modules/firebase-push-notifications/modules/firebase-push-notifications/package.json
  modules/firebase-push-notifications/modules/firebase-push-notifications/utils.js
Labels: module

#397 React native appointment-local module
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/README.md
  modules/firebase-push-notifications/modules/firebase-push-notifications/README.md
  modules/react-native-appointment-local/Navigator/index.js
  modules/react-native-appointment-local/README.md
  modules/react-native-appointment-local/components/AppointmentDetailModal/index.js
  modules/react-native-appointment-local/components/Button/index.js
  modules/react-native-appointment-local/components/InputText/index.js
  modules/react-native-appointment-local/components/Loader/index.js
  modules/react-native-appointment-local/deleteIcon.png
  modules/react-native-appointment-local/index.js
  modules/react-native-appointment-local/meta.json
  modules/react-native-appointment-local/options.js
  modules/react-native-appointment-local/package.json
  modules/react-native-appointment-local/preview.png
  modules/react-native-appointment-local/screens/appointmentList.js
  modules/react-native-appointment-local/screens/appointments.js
  modules/react-native-appointment-local/screens/calendar.js
  modules/react-native-appointment-local/screens/createAppointment.js
  modules/react-native-appointment-local/screens/home .js
  modules/react-native-appointment-local/store/api.js
  modules/react-native-appointment-local/store/index.js
  modules/react-native-appointment-local/utils.js
Labels: module

#743 Schedule-payment screen
  modules/screen-schedule-payment/assets/3Dots.png
  modules/screen-schedule-payment/assets/Card-large.png
  modules/screen-schedule-payment/assets/deleteIcon.png
  modules/screen-schedule-payment/assets/message.png
  modules/screen-schedule-payment/assets/next.png
  modules/screen-schedule-payment/assets/phone.png
  modules/screen-schedule-payment/assets/promo.png
  modules/screen-schedule-payment/assets/rating.png
  modules/screen-schedule-payment/index.js
  modules/screen-schedule-payment/meta.json
  modules/screen-schedule-payment/package.json
  modules/screen-schedule-payment/preview.png
Labels: screen-only

#744 Schedule-wallet screen
  modules/screen-schedule-wallet/assets/3Dots.png
  modules/screen-schedule-wallet/assets/Card-large.png
  modules/screen-schedule-wallet/assets/back.png
  modules/screen-schedule-wallet/assets/background.png
  modules/screen-schedule-wallet/assets/calender.png
  modules/screen-schedule-wallet/assets/deleteIcon.png
  modules/screen-schedule-wallet/assets/home.png
  modules/screen-schedule-wallet/assets/search.png
  modules/screen-schedule-wallet/assets/user.png
  modules/screen-schedule-wallet/assets/walletIcon.png
  modules/screen-schedule-wallet/index.js
  modules/screen-schedule-wallet/meta.json
  modules/screen-schedule-wallet/package.json
  modules/screen-schedule-wallet/preview.png
Labels: screen-only

#745 Schedule-myAppointments screen
  modules/screen-schedule-my-appointments/assets/back.png
  modules/screen-schedule-my-appointments/assets/background.png
  modules/screen-schedule-my-appointments/assets/calender.png
  modules/screen-schedule-my-appointments/assets/home.png
  modules/screen-schedule-my-appointments/assets/next.png
  modules/screen-schedule-my-appointments/assets/prev.png
  modules/screen-schedule-my-appointments/assets/progress.png
  modules/screen-schedule-my-appointments/assets/search.png
  modules/screen-schedule-my-appointments/assets/user.png
  modules/screen-schedule-my-appointments/index.js
  modules/screen-schedule-my-appointments/meta.json
  modules/screen-schedule-my-appointments/package.json
  modules/screen-schedule-my-appointments/preview.png
Labels: screen-only

#746 Schedule-notifications screen
  modules/screen-schedule-notifications/assets/alarm.png
  modules/screen-schedule-notifications/assets/appointment.png
  modules/screen-schedule-notifications/assets/back.png
  modules/screen-schedule-notifications/assets/calender.png
  modules/screen-schedule-notifications/assets/home.png
  modules/screen-schedule-notifications/assets/notification.png
  modules/screen-schedule-notifications/assets/reminder.png
  modules/screen-schedule-notifications/assets/search.png
  modules/screen-schedule-notifications/assets/user.png
  modules/screen-schedule-notifications/index.js
  modules/screen-schedule-notifications/meta.json
  modules/screen-schedule-notifications/package.json
  modules/screen-schedule-notifications/preview.png
Labels: screen-only

#747 Schedule-messages screen
  modules/screen-schedule-messages/assets/back.png
  modules/screen-schedule-messages/assets/calender.png
  modules/screen-schedule-messages/assets/home.png
  modules/screen-schedule-messages/assets/profile1.png
  modules/screen-schedule-messages/assets/profile2.png
  modules/screen-schedule-messages/assets/profile3.png
  modules/screen-schedule-messages/assets/search.png
  modules/screen-schedule-messages/assets/user.png
  modules/screen-schedule-messages/index.js
  modules/screen-schedule-messages/meta.json
  modules/screen-schedule-messages/package.json
  modules/screen-schedule-messages/preview.png
Labels: screen-only

#923 Role and Resources Screen
  modules/screen-role-and-resources/assets/bell-ring.png
  modules/screen-role-and-resources/assets/bullish.png
  modules/screen-role-and-resources/assets/companyLogo.png
  modules/screen-role-and-resources/assets/crowdbotics.jpeg
  modules/screen-role-and-resources/assets/dashboards.png
  modules/screen-role-and-resources/assets/dellLaptop.png
  modules/screen-role-and-resources/assets/logout.png
  modules/screen-role-and-resources/assets/mobile.png
  modules/screen-role-and-resources/assets/page.png
  modules/screen-role-and-resources/assets/rightArrow.png
  modules/screen-role-and-resources/assets/rocket.png
  modules/screen-role-and-resources/assets/surfaceNotebook.png
  modules/screen-role-and-resources/assets/user.png
  modules/screen-role-and-resources/index.js
  modules/screen-role-and-resources/meta.json
  modules/screen-role-and-resources/package.json
  modules/screen-role-and-resources/preview.png
Labels: screen-only

#922 New-Onboarding Screen
  modules/screen-new-onboarding/assets/bell-ring.png
  modules/screen-new-onboarding/assets/bullish.png
  modules/screen-new-onboarding/assets/camera.png
  modules/screen-new-onboarding/assets/companyLogo.png
  modules/screen-new-onboarding/assets/crowdbotics.jpeg
  modules/screen-new-onboarding/assets/dashboards.png
  modules/screen-new-onboarding/assets/logout.png
  modules/screen-new-onboarding/assets/page.png
  modules/screen-new-onboarding/assets/profile.png
  modules/screen-new-onboarding/assets/rightArrow.png
  modules/screen-new-onboarding/assets/rocket.png
  modules/screen-new-onboarding/assets/user.png
  modules/screen-new-onboarding/index.js
  modules/screen-new-onboarding/meta.json
  modules/screen-new-onboarding/package.json
  modules/screen-new-onboarding/preview.png
Labels: screen-only

#918 Load Funds Invoice Screen (Frontend): Optimization for enterprise
  modules/screen-load-funds-invoice/assets/back.png
  modules/screen-load-funds-invoice/index.js
  modules/screen-load-funds-invoice/package.json
  modules/screen-load-funds-invoice/preview.png
Labels: screen-only

#917 Profile Screen (Frontend): Optimization for enterprise
  modules/screen-profile/assets/back.png
  modules/screen-profile/index.js
  modules/screen-profile/package.json
  modules/screen-profile/preview.png
Labels: screen-only

#884 Blackbaud event detail screen
  modules/screen-blackbaud-event-details/index.js
  modules/screen-blackbaud-event-details/meta.json
  modules/screen-blackbaud-event-details/package.json
  modules/screen-blackbaud-event-details/preview.png
Labels: screen-only

#883 Blackbaud eventlist screen
  modules/react-native-appointment-local/index.js
  modules/screen-blackbaud-event-listing/assets/blackbaudLogo.png
  modules/screen-blackbaud-event-listing/assets/calendarIcon.png
  modules/screen-blackbaud-event-listing/index.js
  modules/screen-blackbaud-event-listing/meta.json
  modules/screen-blackbaud-event-listing/package.json
  modules/screen-blackbaud-event-listing/preview.png
  modules/screen-schedule-payment/index.js
  modules/screen-schedule-wallet/index.js
Labels: screen-only

#738 Schedule-search screen
  modules/screen-schedule-search/assets/bone.png
  modules/screen-schedule-search/assets/calender.png
  modules/screen-schedule-search/assets/fsearch.png
  modules/screen-schedule-search/assets/heart.png
  modules/screen-schedule-search/assets/home.png
  modules/screen-schedule-search/assets/lungs.png
  modules/screen-schedule-search/assets/rating.png
  modules/screen-schedule-search/assets/search.png
  modules/screen-schedule-search/assets/user.png
  modules/screen-schedule-search/index.js
  modules/screen-schedule-search/meta.json
  modules/screen-schedule-search/package.json
  modules/screen-schedule-search/preview.png
Labels: screen-only

#737 Schedule-home screen
  modules/screen-schedule-home/assets/bone.png
  modules/screen-schedule-home/assets/calender.png
  modules/screen-schedule-home/assets/file.png
  modules/screen-schedule-home/assets/fsearch.png
  modules/screen-schedule-home/assets/heart.png
  modules/screen-schedule-home/assets/home.png
  modules/screen-schedule-home/assets/lungs.png
  modules/screen-schedule-home/assets/rating.png
  modules/screen-schedule-home/assets/search.png
  modules/screen-schedule-home/assets/star.png
  modules/screen-schedule-home/assets/user.png
  modules/screen-schedule-home/index.js
  modules/screen-schedule-home/meta.json
  modules/screen-schedule-home/package.json
  modules/screen-schedule-home/preview.png
Labels: screen-only

#736 Choose-Category screen
  modules/screen-choose-category/assets/bone.png
  modules/screen-choose-category/assets/eye.png
  modules/screen-choose-category/assets/germs.png
  modules/screen-choose-category/assets/heart.png
  modules/screen-choose-category/assets/lungs.png
  modules/screen-choose-category/assets/muscles.png
  modules/screen-choose-category/assets/stomach.png
  modules/screen-choose-category/assets/teeth.png
  modules/screen-choose-category/index.js
  modules/screen-choose-category/meta.json
  modules/screen-choose-category/package.json
  modules/screen-choose-category/preview.png
Labels: screen-only

#734 Service-provider profile screen
  modules/screen-service-provider-profile/assets/back.png
  modules/screen-service-provider-profile/assets/calender.png
  modules/screen-service-provider-profile/assets/fsearch.png
  modules/screen-service-provider-profile/assets/heart.png
  modules/screen-service-provider-profile/assets/home.png
  modules/screen-service-provider-profile/assets/loc.png
  modules/screen-service-provider-profile/assets/map.png
  modules/screen-service-provider-profile/assets/message.png
  modules/screen-service-provider-profile/assets/phone.png
  modules/screen-service-provider-profile/assets/rating.png
  modules/screen-service-provider-profile/assets/user.png
  modules/screen-service-provider-profile/index.js
  modules/screen-service-provider-profile/meta.json
  modules/screen-service-provider-profile/package.json
  modules/screen-service-provider-profile/preview.png
Labels: screen-only

#733 Signup-3 screen
  modules/screen-signup-3/assets/appleIcon.png
  modules/screen-signup-3/assets/checkboxIcon.png
  modules/screen-signup-3/assets/checkboxIconActive.png
  modules/screen-signup-3/assets/eyeIcon.png
  modules/screen-signup-3/assets/facebookIcon.png
  modules/screen-signup-3/assets/fingerprintIcon.png
  modules/screen-signup-3/assets/googleIcon.png
  modules/screen-signup-3/index.js
  modules/screen-signup-3/meta.json
  modules/screen-signup-3/package.json
  modules/screen-signup-3/preview.png
Labels: screen-only

#732 Login-3 screen
  modules/screen-login-3/assets/appleIcon.png
  modules/screen-login-3/assets/checkboxIcon.png
  modules/screen-login-3/assets/checkboxIconActive.png
  modules/screen-login-3/assets/eyeIcon.png
  modules/screen-login-3/assets/facebookIcon.png
  modules/screen-login-3/assets/fingerprintIcon.png
  modules/screen-login-3/assets/googleIcon.png
  modules/screen-login-3/index.js
  modules/screen-login-3/meta.json
  modules/screen-login-3/package.json
  modules/screen-login-3/preview.png
Labels: screen-only

#731 Welcome-3 Screen
  modules/screen-welcome-3/assets/welcome.png
  modules/screen-welcome-3/index.js
  modules/screen-welcome-3/meta.json
  modules/screen-welcome-3/package.json
  modules/screen-welcome-3/preview.png
Labels: screen-only

#660 screen-staking added
  modules/screen-staking/assets/decrementIcon.png
  modules/screen-staking/assets/incrementIcon.png
  modules/screen-staking/assets/infoIcon.png
  modules/screen-staking/index.js
Labels: screen-only

#652 screen-meetings-list added
  modules/screen-meetings-list/assets/searchIcon.png
  modules/screen-meetings-list/index.js
Labels: screen-only

#651 screen-location-search added
  modules/screen-location-search/assets/checkboxIcon.png
  modules/screen-location-search/assets/checkboxIconActive.png
  modules/screen-location-search/assets/dropdownIcon.png
  modules/screen-location-search/index.js
Labels: screen-only

#650 screen-load-wallet added
  modules/screen-load-wallet/assets/bitcoinIcon.png
  modules/screen-load-wallet/assets/decrementIcon.png
  modules/screen-load-wallet/assets/dollarIcon.png
  modules/screen-load-wallet/assets/euroIcon.png
  modules/screen-load-wallet/assets/incrementIcon.png
  modules/screen-load-wallet/assets/poundIcon.png
  modules/screen-load-wallet/index.js
Labels: screen-only

#835 Typeform Webhook Module (Super): Optimization for enterprise
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/README.md
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/admin.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/migrations/0001_initial.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/models.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/options.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/serializers.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/tests.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/urls.py
  modules/django-typeform-webhook/django_typeform_webhook/typeform_webhook/viewsets.py
  modules/react-native-typeform-webhook/README.md
  modules/react-native-typeform-webhook/api/index.js
  modules/react-native-typeform-webhook/components/FormItem/index.js
  modules/react-native-typeform-webhook/components/Loader/index.js
  modules/react-native-typeform-webhook/components/Response/index.js
  modules/react-native-typeform-webhook/index.js
  modules/react-native-typeform-webhook/options.js
  modules/react-native-typeform-webhook/screen/Responses.js
  modules/react-native-typeform-webhook/screen/TypeformWebhook.js
  modules/react-native-typeform-webhook/store/api.js
  modules/react-native-typeform-webhook/store/index.js
  modules/react-native-typeform-webhook/utils.js
Labels: module

#912 Fix: React Native fingerprint authentication (0.71.7)
  modules/react-native-fingerprint-authentication/README.md
  modules/react-native-fingerprint-authentication/index.js
  modules/react-native-fingerprint-authentication/package.json
Labels: module

#684 PDF Viewer module
  modules/react-native-pdf-viewer/Loader/index.js
  modules/react-native-pdf-viewer/README.md
  modules/react-native-pdf-viewer/index.js
  modules/react-native-pdf-viewer/meta.json
  modules/react-native-pdf-viewer/options.js
  modules/react-native-pdf-viewer/package.json
  modules/react-native-pdf-viewer/preview.png
Labels: module

#920 Two Factor Authentication Module (Backend): Optimization for enterprise
  modules/django-two-factor-authentication/django_two_factor_authentication/setup.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/README.md
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/admin.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/apps.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/migrations/0001_initial.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/models.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/serializers.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/service/TwoFactorAuthenticationService.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/tests.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/urls.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/utils.py
  modules/django-two-factor-authentication/django_two_factor_authentication/two_factor_authentication/viewsets.py
Labels: module

#919 Two Factor Authentication Module (Frontend): Optimization for enterprise
  modules/react-native-2fa/README.md
  modules/react-native-2fa/components/Button/index.js
  modules/react-native-2fa/components/Input/index.js
  modules/react-native-2fa/index.js
  modules/react-native-2fa/navigator/index.js
  modules/react-native-2fa/options.js
  modules/react-native-2fa/package.json
  modules/react-native-2fa/preview.png
  modules/react-native-2fa/screens/authTypes/index.js
  modules/react-native-2fa/screens/googleAuth/index.js
  modules/react-native-2fa/screens/verification/index.js
  modules/react-native-2fa/store/api.js
  modules/react-native-2fa/store/index.js
  modules/react-native-2fa/utils.js
  modules/screen-blackbaud-event-details/index.js
  modules/screen-location-search/index.js
Labels: module

#900 Fix: React Native app-menu (0.71.7)
  modules/react-native-app-menu/README.md
Labels: module

#896 Django OpenAI Module
  modules/django-openai/django_openai/openai/README.md
  modules/django-openai/django_openai/openai/__init__.py
  modules/django-openai/django_openai/openai/admin.py
  modules/django-openai/django_openai/openai/apps.py
  modules/django-openai/django_openai/openai/migrations/__init__.py
  modules/django-openai/django_openai/openai/models.py
  modules/django-openai/django_openai/openai/options.py
  modules/django-openai/django_openai/openai/serializers.py
  modules/django-openai/django_openai/openai/services/OpenAIServices.py
  modules/django-openai/django_openai/openai/tests.py
  modules/django-openai/django_openai/openai/urls.py
  modules/django-openai/django_openai/openai/viewsets.py
  modules/django-openai/django_openai/pyproject.toml
  modules/django-openai/django_openai/setup.py
  modules/django-openai/meta.json
  modules/django-openai/preview.png
Labels: module

#864 Contact us store implementation and Update readme
  modules/django-contact-us/django_contact_us/contact_us/README.md
  modules/react-native-contact-us/README.md
  modules/react-native-contact-us/index.js
  modules/react-native-contact-us/preview.png
  modules/react-native-contact-us/screens/ContactForm.js
  modules/react-native-contact-us/store/api.js
  modules/react-native-contact-us/store/index.js
Labels: module

#847 Upgrade and Fix: React Native youtube player (0.71.7)
  modules/react-native-youtube-player/README.md
Labels: module

#837 Add Readme : Zoom Info Module
  modules/django-zoom-info/django_zoom_info/zoominfo/README.md
Labels: module

#836 Files Module (Backend): Optimization for enterprise
  modules/django-files/django_files/files/README.md
  modules/django-files/django_files/files/models.py
  modules/django-files/django_files/files/serializers.py
  modules/django-files/django_files/files/tests.py
  modules/django-files/django_files/files/urls.py
  modules/django-files/django_files/files/viewsets.py
Labels: module

#789 Drive Module (Backend): Optimization for enterprise
  modules/django-drive/django_drive/drive/README.md
  modules/django-drive/django_drive/drive/apps.py
  modules/django-drive/django_drive/drive/serializers.py
  modules/django-drive/django_drive/drive/services/Drive.py
  modules/django-drive/django_drive/drive/services/DriveService.py
  modules/django-drive/django_drive/drive/tests.py
  modules/django-drive/django_drive/drive/urls.py
  modules/django-drive/django_drive/drive/viewsets.py
Labels: module

#781 Test Cases: Django HubSpot
  modules/django-hubspot/django_hubspot/hubspot/README.md
  modules/django-hubspot/django_hubspot/hubspot/serializers.py
  modules/django-hubspot/django_hubspot/hubspot/services/HubspotService.py
  modules/django-hubspot/django_hubspot/hubspot/tests.py
  modules/django-hubspot/django_hubspot/hubspot/viewsets.py
Labels: module

#689 Image Gallery module
  modules/react-native-image-gallery/README.md
  modules/react-native-image-gallery/index.js
  modules/react-native-image-gallery/meta.json
  modules/react-native-image-gallery/options.js
  modules/react-native-image-gallery/package.json
  modules/react-native-image-gallery/preview.png
  modules/react-native-image-gallery/utils.js
Labels: module

#410 React native terms-and-conditions module
  modules/react-native-terms-and-conditions/README.md
  modules/react-native-terms-and-conditions/index.js
  modules/react-native-terms-and-conditions/meta.json
  modules/react-native-terms-and-conditions/options.js
  modules/react-native-terms-and-conditions/package.json
  modules/react-native-terms-and-conditions/preview.png
  modules/react-native-terms-and-conditions/store/api.js
  modules/react-native-terms-and-conditions/store/index.js
  modules/react-native-terms-and-conditions/styles.js
Labels: module

#405 React native privacy-policy module
  modules/react-native-privacy-policy/README.md
  modules/react-native-privacy-policy/index.js
  modules/react-native-privacy-policy/meta.json
  modules/react-native-privacy-policy/package.json
  modules/react-native-privacy-policy/preview.png
  modules/react-native-privacy-policy/store/api.js
  modules/react-native-privacy-policy/store/index.js
  modules/react-native-privacy-policy/styles.js
Labels: module

#391 User-profile module
  modules/react-native-user-profile/README.md
  modules/react-native-user-profile/edit.js
  modules/react-native-user-profile/index.js
  modules/react-native-user-profile/package.json
  modules/react-native-user-profile/store/api.js
  modules/react-native-user-profile/store/index.js
  modules/react-native-user-profile/view.js
Labels: module

#403 React native camera module
  modules/react-native-camera/README.md
  modules/react-native-camera/index.js
  modules/react-native-camera/meta.json
  modules/react-native-camera/options.js
  modules/react-native-camera/package.json
  modules/react-native-camera/preview.png
  modules/react-native-camera/store/api.js
  modules/react-native-camera/store/index.js
  modules/react-native-camera/utils.js
Labels: module

#406 Fix naming: Django Privacy-policy
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/README.md
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/__init__.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/admin.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/apps.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/migrations/0001_privacy_initial.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/migrations/__init__.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/models.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/options.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/serializers.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/urls.py
  modules/django-privacy-policy/django_privacy_policy/privacy_policy/viewsets.py
  modules/django-privacy-policy/django_privacy_policy/pyproject.toml
  modules/django-privacy-policy/django_privacy_policy/setup.py
  modules/django-privacy-policy/meta.json
  modules/django-privacy-policy/preview.png
  modules/privacy-policy/backend/modules/privacy_policy/privacy_policy/README.md
  modules/privacy-policy/backend/modules/privacy_policy/setup.py
  modules/privacy-policy/meta.json
  modules/privacy-policy/modules/privacy-policy/README.md
  modules/privacy-policy/modules/privacy-policy/index.js
  modules/privacy-policy/modules/privacy-policy/package.json
  modules/privacy-policy/modules/privacy-policy/styles.js
Labels: module

#411 Fix naming: Django terms-and-conditions
  modules/django-terms-and-conditions/django_terms_and_conditions/pyproject.toml
  modules/django-terms-and-conditions/django_terms_and_conditions/setup.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/README.md
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/__init__.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/admin.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/apps.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/migrations/0001_terms_initial.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/migrations/__init__.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/models.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/options.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/serializers.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/urls.py
  modules/django-terms-and-conditions/django_terms_and_conditions/terms_and_conditions/viewsets.py
  modules/django-terms-and-conditions/meta.json
  modules/django-terms-and-conditions/preview.png
  modules/terms-and-conditions/backend/modules/terms_and_conditions/terms_and_conditions/README.md
  modules/terms-and-conditions/meta.json
  modules/terms-and-conditions/modules/terms-and-conditions/README.md
  modules/terms-and-conditions/modules/terms-and-conditions/index.js
  modules/terms-and-conditions/modules/terms-and-conditions/options.js
  modules/terms-and-conditions/modules/terms-and-conditions/package.json
  modules/terms-and-conditions/modules/terms-and-conditions/styles.js
Labels: module

#632 Google Autocomplete module
  modules/react-native-address-selection-google-autocomplete/Navigator/index.js
  modules/react-native-address-selection-google-autocomplete/README.md
  modules/react-native-address-selection-google-autocomplete/index.js
  modules/react-native-address-selection-google-autocomplete/meta.json
  modules/react-native-address-selection-google-autocomplete/options.js
  modules/react-native-address-selection-google-autocomplete/package.json
  modules/react-native-address-selection-google-autocomplete/preview.png
  modules/react-native-address-selection-google-autocomplete/screens/addressAutocomplete.js
  modules/react-native-address-selection-google-autocomplete/screens/map.js
Labels: module

#633 Side Drawer Module
  modules/react-native-side-drawer/README.md
  modules/react-native-side-drawer/index.js
  modules/react-native-side-drawer/meta.json
  modules/react-native-side-drawer/options.js
  modules/react-native-side-drawer/package.json
  modules/react-native-side-drawer/preview.png
Labels: module

#849 Updated-Readme: Onboarding Module
  modules/react-native-onboarding/README.md
Labels: module

#785 Django mailchimp
  modules/django-mailchimp/django_mailchimp/mailchimp/README.md
  modules/django-mailchimp/django_mailchimp/mailchimp/__init__.py
  modules/django-mailchimp/django_mailchimp/mailchimp/admin.py
  modules/django-mailchimp/django_mailchimp/mailchimp/apps.py
  modules/django-mailchimp/django_mailchimp/mailchimp/migrations/__init__.py
  modules/django-mailchimp/django_mailchimp/mailchimp/models.py
  modules/django-mailchimp/django_mailchimp/mailchimp/serializers.py
  modules/django-mailchimp/django_mailchimp/mailchimp/services/MailchimpService.py
  modules/django-mailchimp/django_mailchimp/mailchimp/tests.py
  modules/django-mailchimp/django_mailchimp/mailchimp/urls.py
  modules/django-mailchimp/django_mailchimp/mailchimp/viewsets.py
  modules/django-mailchimp/django_mailchimp/pyproject.toml
  modules/django-mailchimp/django_mailchimp/setup.py
  modules/django-mailchimp/meta.json
  modules/django-mailchimp/preview.png
Labels: module

#726 JSON Renderer and MIDDLEWARE
  modules/django-core/django_core/core/README.md
  modules/django-core/django_core/core/__init__.py
  modules/django-core/django_core/core/exception_handler.py
  modules/django-core/django_core/core/response_renderer.py
  modules/django-core/django_core/pyproject.toml
  modules/django-core/django_core/setup.py
  modules/django-core/meta.json
  modules/django-core/preview.png
Labels: module

#404 Django camera
  modules/django-camera/django_camera/camera/README.md
  modules/django-camera/django_camera/camera/__init__.py
  modules/django-camera/django_camera/camera/admin.py
  modules/django-camera/django_camera/camera/apps.py
  modules/django-camera/django_camera/camera/migrations/0001_initial.py
  modules/django-camera/django_camera/camera/migrations/__init__.py
  modules/django-camera/django_camera/camera/models.py
  modules/django-camera/django_camera/camera/options.py
  modules/django-camera/django_camera/camera/serializers.py
  modules/django-camera/django_camera/camera/urls.py
  modules/django-camera/django_camera/camera/viewsets.py
  modules/django-camera/django_camera/setup.py
  modules/django-camera/meta.json
  modules/django-camera/preview.png
Labels: module

#850 Updated-Readme: Wallet Connect Module
  modules/react-native-wallet-connect/README.md
Labels: module

#853 Updated-Readme: Login Module
  modules/react-native-login/README.md
Labels: module

#856 Updated-Readme: Terms And Conditions Webview
  modules/react-native-terms-and-conditions-webview/README.md
Labels: module

#848 Upgrade and Fix: React Native chat (0.71.7)
  modules/react-native-chat/README.md
  modules/react-native-chat/package.json
  modules/react-native-chat/preview.png
Labels: module

#773 Django Google Appointment
  modules/django-google-appointment/django_google_appointment/appointment/README.md
  modules/django-google-appointment/django_google_appointment/appointment/__init__.py
  modules/django-google-appointment/django_google_appointment/appointment/admin.py
  modules/django-google-appointment/django_google_appointment/appointment/apps.py
  modules/django-google-appointment/django_google_appointment/appointment/migrations/0001_initial.py
  modules/django-google-appointment/django_google_appointment/appointment/migrations/__init__.py
  modules/django-google-appointment/django_google_appointment/appointment/models.py
  modules/django-google-appointment/django_google_appointment/appointment/options.py
  modules/django-google-appointment/django_google_appointment/appointment/serializers.py
  modules/django-google-appointment/django_google_appointment/appointment/services/GoogleAppointmentServices.py
  modules/django-google-appointment/django_google_appointment/appointment/tests.py
  modules/django-google-appointment/django_google_appointment/appointment/urls.py
  modules/django-google-appointment/django_google_appointment/appointment/viewsets.py
  modules/django-google-appointment/django_google_appointment/pyproject.toml
  modules/django-google-appointment/django_google_appointment/setup.py
  modules/django-google-appointment/meta.json
  modules/django-google-appointment/preview.png
Labels: module

#683 Audio-Player module
  modules/react-native-audio-player/README.md
  modules/react-native-audio-player/index.js
  modules/react-native-audio-player/meta.json
  modules/react-native-audio-player/options.js
  modules/react-native-audio-player/package.json
  modules/react-native-audio-player/playButton.js
  modules/react-native-audio-player/preview.png
  modules/react-native-audio-player/styles.js
  modules/react-native-audio-player/trackList.js
Labels: module

#776 Disqus Module (Backend): Optimization for enterprise
  modules/django-disqus/django_disqus/disqus/README.md
  modules/django-disqus/django_disqus/disqus/__init__.py
  modules/django-disqus/django_disqus/disqus/admin.py
  modules/django-disqus/django_disqus/disqus/apps.py
  modules/django-disqus/django_disqus/disqus/migrations/0001_initial.py
  modules/django-disqus/django_disqus/disqus/migrations/__init__.py
  modules/django-disqus/django_disqus/disqus/models.py
  modules/django-disqus/django_disqus/disqus/options.py
  modules/django-disqus/django_disqus/disqus/pagination.py
  modules/django-disqus/django_disqus/disqus/serializers.py
  modules/django-disqus/django_disqus/disqus/tests.py
  modules/django-disqus/django_disqus/disqus/urls.py
  modules/django-disqus/django_disqus/disqus/viewsets.py
  modules/django-disqus/django_disqus/pyproject.toml
  modules/django-disqus/django_disqus/setup.py
  modules/django-disqus/meta.json
  modules/django-disqus/preview.png
Labels: module

#634 Social Login Module (Backend): Optimization for enterprise
  modules/django-social-auth/django_social_auth/setup.py
  modules/django-social-auth/django_social_auth/social_auth/README.md
  modules/django-social-auth/django_social_auth/social_auth/serializers.py
  modules/django-social-auth/django_social_auth/social_auth/tests.py
  modules/django-social-auth/django_social_auth/social_auth/urls.py
  modules/django-social-auth/django_social_auth/social_auth/views.py
Labels: module

#937 PLAT-11982 add JIRA labels
  .github/workflows/release.yml
Labels: devops
