Repository crowdbotics/modules, pull requests merged in 2023-10, with the labels that each got.

#953 PLAT-12152: adding parameters to update modules command
  .github/workflows/release.yml
Labels: devops, blocked

#215 Subscription v0.1
  modules/subscription/backend/modules/subscription/README.md
  modules/subscription/backend/modules/subscription/__init__.py
  modules/subscription/backend/modules/subscription/admin.py
  modules/subscription/backend/modules/subscription/apps.py
  modules/subscription/backend/modules/subscription/migrations/0001_initial.py
  modules/subscription/backend/modules/subscription/migrations/__init__.py
  modules/subscription/backend/modules/subscription/models.py
  modules/subscription/backend/modules/subscription/serializers.py
  modules/subscription/backend/modules/subscription/services/StripeSubscriptionService.py
  modules/subscription/backend/modules/subscription/templates/index.html
  modules/subscription/backend/modules/subscription/urls.py
  modules/subscription/backend/modules/subscription/viewsets.py
  modules/subscription/meta.json
  modules/subscription/modules/subscription/README.md
  modules/subscription/modules/subscription/api.js
  modules/subscription/modules/subscription/index.js
  modules/subscription/modules/subscription/options.js
  modules/subscription/modules/subscription/package.json
  modules/subscription/modules/subscription/preview.png
  modules/subscription/preview.png
Labels: module, blocked

#846 Fix: Google Analytics module (0.71.7)
  modules/react-native-google-analytics/README.md
Labels: module

#926 Social module
  modules/social-feed/backend/modules/social-feed/README.md
  modules/social-feed/backend/modules/social-feed/__init__.py
  modules/social-feed/backend/modules/social-feed/admin.py
  modules/social-feed/backend/modules/social-feed/apps.py
  modules/social-feed/backend/modules/social-feed/migrations/0001_initial.py
  modules/social-feed/backend/modules/social-feed/migrations/__init__.py
  modules/social-feed/backend/modules/social-feed/models.py
  modules/social-feed/backend/modules/social-feed/pagination.py
  modules/social-feed/backend/modules/social-feed/serializers.py
  modules/social-feed/backend/modules/social-feed/tests.py
  modules/social-feed/backend/modules/social-feed/urls.py
  modules/social-feed/backend/modules/social-feed/views.py
  modules/social-feed/backend/modules/social-feed/viewsets.py
  modules/social-feed/meta.json
  modules/social-feed/modules/social-feed/README.md
  modules/social-feed/modules/social-feed/assets/add-photo.png
  modules/social-feed/modules/social-feed/assets/comment.png
  modules/social-feed/modules/social-feed/assets/dots.png
  modules/social-feed/modules/social-feed/assets/edit.png
  modules/social-feed/modules/social-feed/assets/following.png
  modules/social-feed/modules/social-feed/assets/group.png
  modules/social-feed/modules/social-feed/assets/like.png
  modules/social-feed/modules/social-feed/assets/plus.png
  modules/social-feed/modules/social-feed/assets/posts.png
  modules/social-feed/modules/social-feed/assets/search.png
  modules/social-feed/modules/social-feed/assets/send.png
  modules/social-feed/modules/social-feed/assets/tempImage.png
  modules/social-feed/modules/social-feed/assets/test.png
  modules/social-feed/modules/social-feed/assets/unlike.png
  modules/social-feed/modules/social-feed/assets/user.png
  modules/social-feed/modules/social-feed/components/comment.js
  modules/social-feed/modules/social-feed/components/post.js
  modules/social-feed/modules/social-feed/index.js
  modules/social-feed/modules/social-feed/navigator/index.js
  modules/social-feed/modules/social-feed/options.js
  modules/social-feed/modules/social-feed/package.json
  modules/social-feed/modules/social-feed/screens/create-post.js
  modules/social-feed/modules/social-feed/screens/followers.js
  modules/social-feed/modules/social-feed/screens/following.js
  modules/social-feed/modules/social-feed/screens/post-details.js
  modules/social-feed/modules/social-feed/screens/social-feed.js
  modules/social-feed/modules/social-feed/screens/social-profile.js
  modules/social-feed/modules/social-feed/store/api.js
  modules/social-feed/modules/social-feed/store/index.js
  modules/social-feed/modules/social-feed/utils.js
  modules/social-feed/preview.png
Labels: module

#973 Add setup images for react-native-google-analytics
  preview/GA-Setup1.png
  preview/GA-Setup2.png
Labels: module

#813 Phone Number Picker Module
  modules/screen-phone-number-picker/index.js
  modules/screen-phone-number-picker/meta.json
  modules/screen-phone-number-picker/package.json
  modules/screen-phone-number-picker/preview.png
Labels: screen-only

#980 PLAT-12373 Add deployment instruction for azure module
  modules/azure-infra/README.md
Labels: module

#996 fix django/react-native meta.json and files paths
  scripts/create.js
Labels: tools

#913 Upgrade and Fix: React Native live camera filters (0.71.7)
  modules/react-native-live-camera-filters/README.md
  modules/react-native-live-camera-filters/components/Filter/index.js
  modules/react-native-live-camera-filters/index.js
  modules/react-native-live-camera-filters/options.js
  modules/react-native-live-camera-filters/package.json
Labels: module

#984 Update react-native-youtube-player package and readme
  modules/react-native-youtube-player/README.md
  modules/react-native-youtube-player/index.js
  modules/react-native-youtube-player/options.js
  modules/react-native-youtube-player/package.json
Labels: module

#985 Social Feed Module (Bug Fixes)
  modules/social-feed/backend/modules/social-feed/views.py
Labels: module

#986 Profile Module (Bug Fixes)
  modules/profile/backend/modules/profile/profile/migrations/0001_initial.py
  modules/profile/backend/modules/profile/profile/models.py
  modules/profile/backend/modules/profile/setup.py
Labels: module

#992 Admin Push Notification Firebase (Super)
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/README.md
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/admin.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/forms.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/migrations/0001_initial.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/models.py
  modules/firebase-push-notifications/backend/modules/firebase_push_notifications/firebase-push-notifications/static/admin/css/custom-notification-admin.css
Labels: module

#993 Update device registration endpoint (Bug Fixes)
  modules/firebase-push-notifications/modules/firebase-push-notifications/api.js
Labels: module

#994 Update destination path for files (Bug Fixes)
  modules/react-native-chat/utils.js
Labels: module

#997 Django Inventory Management Module (Backend)
  modules/django-inventory-management/django_inventory_management/inventory_management/README.md
  modules/django-inventory-management/django_inventory_management/inventory_management/__init__.py
  modules/django-inventory-management/django_inventory_management/inventory_management/admin.py
  modules/django-inventory-management/django_inventory_management/inventory_management/apps.py
  modules/django-inventory-management/django_inventory_management/inventory_management/migrations/0001_initial.py
  modules/django-inventory-management/django_inventory_management/inventory_management/migrations/__init__.py
  modules/django-inventory-management/django_inventory_management/inventory_management/models.py
  modules/django-inventory-management/django_inventory_management/inventory_management/options.py
  modules/django-inventory-management/django_inventory_management/inventory_management/serializers.py
  modules/django-inventory-management/django_inventory_management/inventory_management/tests.py
  modules/django-inventory-management/django_inventory_management/inventory_management/urls.py
  modules/django-inventory-management/django_inventory_management/inventory_management/viewsets.py
  modules/django-inventory-management/django_inventory_management/pyproject.toml
  modules/django-inventory-management/django_inventory_management/setup.py
  modules/django-inventory-management/meta.json
  modules/django-inventory-management/preview.png
Labels: module
